flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import Blueprint, request, render_template
from flaskblog.models import Post

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home') # add multiple decorators to allow the same function to be accessed via multiple routes
def home():
    page = request.args.get('page', 1, type=int)  # sets default page to 1, and throws error if not an integer
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=3, page=page)
    return render_template('home.html', posts=posts)

# homepage is paginated
# access multiple pages via eg http://localhost:5000/home?page=3


@main.route('/about')
def about():
    return render_template('about.html', title='About')

flaskblog/posts/routes.py
from flask import (Blueprint, render_template, url_for, flash, redirect, request, abort)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created.','success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='Create Post')


@posts.route('/post/<int:post_id>', methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id) #i.e. if post with post_id doesn't exist return a 404 error
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)  # http code for forbidden route
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit() # no add needed as this is an update to the db entries
        flash('Post has been updated.', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route('/post/<int:post_id>/delete', methods=['POST']) # i.e. only posts allowed as it can only be accessed via modal submit
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)  # http code for forbidden route
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted.', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import Blueprint, flash, redirect, url_for, render_template, request
from flask_login import current_user, login_required, login_user, logout_user
from flaskblog.models import User, Post
from flaskblog import db, bcrypt
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, ResetPasswordForm, RequestResetForm
from flaskblog.users.utils import save_picture, send_reset_email



users = Blueprint('users', __name__)


@users.route('/register', methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        # hash the password
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        # redirect to homepage if successful registration
        flash(f'Registration successful for {form.username.data}! You are now able to log in.', 'success')
        return redirect(url_for('users.login')) # NAME OF THE FUNCTION FOR THAT ROUTE
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # log them in using flask_login extension
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next') # returns None if 'next' parameter not present in URL
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
            # next_page = '/account', therefore we don't use url_for(next_page), as the / already means it's a url
        else:
            flash('Login unsuccessful. Please check email and password', 'danger')
            # danger = red alerting bootstrap class
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            # set the user's profile picture, and add it to the database
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated.', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename = 'profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)



@users.route('/home/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)  # sets default page to 1, and throws error if not an integer
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(per_page=3, page=page)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        # find the user corresponding to the submitted email
        user = User.query.filter_by(email=form.email.data).first()
        # send this user a reset password link by email
        send_reset_email(user)
        flash('An email has been sent with instructions on how to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form, legend='Reset Password')


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):  #i.e. reset the password with the reset token
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        # hash the password
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pw
        db.session.commit()
        # redirect to homepage if successful registration
        flash(f'Your password has been reset. You are now able to log in.', 'success')
        return redirect(url_for('users.login'))  # NAME OF THE FUNCTION FOR THAT ROUTE
    return render_template('reset_token.html', title='Reset Password', form=form, legend='Reset Password')

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
  <h1>{{ title }}</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
  <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ image_file }}" width="100" height="100">
      <div class="media-body">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>
      </div>
    </div>
    <div class="content-section">
        <form method="POST" action="" enctype="multipart/form-data"> <!-- DON'T FORGET ENCTYPE! -->
            {{ form.hidden_tag() }} <!-- protection against XSRF -->
            <fieldset class="form-group">
              <legend class="border-bottom mb-4">Update Account Info</legend>
              <div class="form-group">
                  {{ form.username.label(class="form-control-label") }}
                  {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.email.label(class="form-control-label") }}
                  {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.picture.label() }}
                  {{ form.picture(class="form-control-file") }}
                  {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                      <span class="text-danger">{{ error }}</span><br>
                    {% endfor %}
                  {% endif %}
              </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
  </div>
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
  <h1>{{ title }}</h1>
  <div class="content-section">
      <form method="POST" action="">
          {{ form.hidden_tag() }} <!-- protection against XSRF -->
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">{{ legend }}</legend>
              <div class="form-group">
                  {{ form.title.label(class="form-control-label") }}
                  {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.content.label(class="form-control-label") }}
                  {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
      </form>
  </div>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
  {% for post in posts.items %}
    <h3><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h3>
    <img class="rounded-circle" width="100" height="100" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <p> By <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a> on {{ post.date_posted.strftime('%Y-%m-%d') }}</p>
    <p>{{ post.content }}</p>
  {% endfor %}
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<!-- layout.html is the parent html file, from which all the other templates inherit -->
<!-- saves copying code across numerous files -->
<html lang="en">
  <head>
    <!-- Required Meta Tags (bootstrap) -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Custom static CSS -->
    <!-- use url_for for as many links as possible within the project -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <!-- JINJA2 SYNTAX: CODEBLOCKS -->
    {% if title %}
      <title>Flask Blog - {{ title }}</title>
    {% else %}
      <title>Flask Blog</title>
    {% endif %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{ url_for('main.home') }}">Jeremy's Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
          </li>
          {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('posts.new_post') }}">Create Post</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('users.login') }}">Log In</a>
            </li>
          {% endif %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown link
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>

    <div class='container'>
      <!-- FLASH MESSAGES HERE -->
      {% with messages = get_flashed_messages(with_categories=true) %} <!-- with_categories gets the 'success' etc label -->
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript at the end of the layout content block-->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
  <h1>{{ title }}</h1>
  <div class="content-section">
      <form method="POST" action="">
          {{ form.hidden_tag() }} <!-- protection against XSRF -->
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Log In</legend>
              <div class="form-group">
                  {{ form.email.label(class="form-control-label") }}
                  {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.password.label(class="form-control-label") }}
                  {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-check">
                  {{ form.remember(class='form-check-input') }}
                  {{ form.remember.label(class='form-check-label') }}
              </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
      </form>
      <small class="text-muted ml-2">
        <a class="ml-s" href="{{ url_for('users.reset_request') }}">I forgot my password</a>
      </small>
  </div>
  <div class="border-top pt-3">
    <small class="text-muted ml-2">
        Don't have an account?<a class="ml-s" href="{{ url_for('users.register') }}">Register here</a>
    </small>
  </div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <h1>{{ title }}</h1>
  <img class="rounded-circle" width="100" height="100" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
  <p> By <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a> on {{ post.date_posted.strftime('%Y-%m-%d') }}</p>
  <p>{{ post.content }}</p>
  {% if post.author == current_user %}
    <div>
      <a class="btn btn-secondary btn-sm m-1" href=" {{ url_for('posts.update_post', post_id = post.id) }} ">Update</a>
      <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
      <!-- Modal -->
      <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Warning!</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Are you absolutely sure you want to delete this post?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input type="submit" class="btn btn-danger" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock content %}

flaskblog/templates/register.html
{% extends "layout.html" %}
{% block content %}
  <h1>{{ title }}</h1>
  <div class="content-section">
      <form method="POST" action="">
          {{ form.hidden_tag() }} <!-- protection against XSRF -->
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Join Today</legend>
              <div class="form-group">
                  {{ form.username.label(class="form-control-label") }}
                  {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.email.label(class="form-control-label") }}
                  {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.password.label(class="form-control-label") }}
                  {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.confirm_password.label(class="form-control-label") }}
                  {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
      </form>
  </div>
  <div class="border-top pt-3">
    <small class="text-muted">
        Already have an account?<a class="ml-s" href="{{ url_for('users.login') }}">Sign In</a>
    </small>
  </div>

{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
  <h1>{{ title }}</h1>
  <div class="content-section">
      <form method="POST" action="">
          {{ form.hidden_tag() }} <!-- protection against XSRF -->
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">{{ legend }}</legend>
              <div class="form-group">
                  {{ form.email.label(class="form-control-label") }}
                  {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
      </form>
  </div>
{% endblock content %}

flaskblog/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
  <h1>{{ title }}</h1>
  <div class="content-section">
      <form method="POST" action="">
          {{ form.hidden_tag() }} <!-- protection against XSRF -->
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">{{ legend }}</legend>
              <div class="form-group">
                  {{ form.password.label(class="form-control-label") }}
                  {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.confirm_password.label(class="form-control-label") }}
                  {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
      </form>
  </div>
{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
  <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
  {% for post in posts.items %}
    <h3><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h3>
    <img class="rounded-circle" width="100" height="100" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <p> By <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a> on {{ post.date_posted.strftime('%Y-%m-%d') }}</p>
    <p>{{ post.content }}</p>
  {% endfor %}
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}
{% endblock content %}